// Generated by CoffeeScript 1.6.3
var Q, cp, readline;

cp = require('child_process');

readline = require('readline');

Q = require('q');

module.exports = function(opts) {
  opts = opts || {};
  return this.act(function() {
    var defer, input, output, prompt, rl;
    defer = Q.defer();
    prompt = opts.prompt || process.env.PS2 || '> ';
    input = opts.input || process.stdin;
    output = opts.output || process.stdout;
    rl = readline.createInterface({
      input: input,
      output: output,
      terminal: true
    });
    rl.setPrompt(prompt, prompt.length);
    rl.on('line', function(line) {
      var child;
      if (!(line = line.trim())) {
        return r1.prompt();
      }
      child = cp.spawn(process.argv[0], process.argv.slice(1, 2).concat(line.split(' ')), {
        cwd: process.cwd(),
        customFds: [-1, 1, 2]
      });
      return child.on('exit', function() {
        return rl.prompt();
      });
    }).on('close', function() {
      output.write('\n');
      process.stdin.destroy();
      return defer.resolve();
    });
    output.write('Type \'--help\' for help, press ctrl+d or ctrl+c to exit\n');
    rl.prompt();
    return defer.promise;
  });
};
